server.port=${PORT:10000}

# Thay th? b?ng URL b?n v?a copy (Nh? ph?i có ch? jdbc: ? ??u nhé)
spring.datasource.url=jdbc:postgresql://ep-gentle-wildflower-am0wg2mp-pooler.c-5.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_gjhmFy2kX7UV&sslmode=require&channelBinding=require
# ?i?n user c?a Neon
spring.datasource.username=neondb_owner

# ?i?n cái m?t kh?u mà b?n v?a b?m hình con m?t ?? hi?n ra
spring.datasource.password=npg_gjhmFy2kX7UV

spring.datasource.driver-class-name=org.postgresql.Driver