DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE nhan_vien (
  id_nhan_vien INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ho_ten VARCHAR(255) NOT NULL,
  gioi_tinh VARCHAR(10),
  tuoi INTEGER,
  luong DOUBLE PRECISION,
  thoi_gian_gan_bo INTEGER,
  diem_thuong INTEGER,
  diem_danh INTEGER,
  so_dien_thoai VARCHAR(20),
  dia_chi VARCHAR(255),
  chuc_vu VARCHAR(100),
  ngay_vao_lam TIMESTAMP
);

CREATE TABLE khach_hang (
  id_kh INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_kh VARCHAR(255) NOT NULL,
  nam_sinh_kh INTEGER,
  diem_thuong_kh INTEGER,
  so_dien_thoai VARCHAR(20),
  dia_chi VARCHAR(255),
  gioi_tinh VARCHAR(10)
);

CREATE TABLE khuyen_mai (
  id_khuyen_mai INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_khuyen_mai VARCHAR(255) NOT NULL,
  phan_tram_giam DOUBLE PRECISION NOT NULL,
  ngay_bat_dau TIMESTAMP,
  ngay_ket_thuc TIMESTAMP,
  mo_ta TEXT
);

CREATE TABLE loai_san_pham (
  id_loai INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_loai VARCHAR(255) NOT NULL,
  hinh_anh BYTEA
);

CREATE TABLE nha_cung_cap (
  id_ncc INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_ncc VARCHAR(255) NOT NULL,
  so_dien_thoai VARCHAR(20) NOT NULL,
  dia_chi VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  ngay_hop_tac TIMESTAMP NOT NULL
);

CREATE TABLE san_pham (
  id_sp INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_sp VARCHAR(255) NOT NULL,
  gia_sp DOUBLE PRECISION NOT NULL,
  tong_so_luong_sp_trong_kho INTEGER NOT NULL,
  id_loai INTEGER NOT NULL,
  don_vi_tinh VARCHAR(50),
  mo_ta TEXT,
  CONSTRAINT fk_san_pham_loai
    FOREIGN KEY (id_loai) REFERENCES loai_san_pham (id_loai)
    ON UPDATE CASCADE
);

CREATE TABLE phieu_nhap (
  id_phieu_nhap INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ncc INTEGER NOT NULL,
  id_nhan_vien INTEGER NOT NULL,
  ngay_nhap TIMESTAMP NOT NULL,
  tong_tien DOUBLE PRECISION NOT NULL,
  ghi_chu TEXT,
  CONSTRAINT fk_phieu_nhap_ncc
    FOREIGN KEY (id_ncc) REFERENCES nha_cung_cap (id_ncc)
    ON UPDATE CASCADE,
  CONSTRAINT fk_phieu_nhap_nhan_vien
    FOREIGN KEY (id_nhan_vien) REFERENCES nhan_vien (id_nhan_vien)
    ON UPDATE CASCADE
);

CREATE TABLE hoa_don (
  id_hoa_don INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_kh INTEGER NOT NULL,
  id_nhan_vien INTEGER NOT NULL,
  ngay_lap TIMESTAMP NOT NULL,
  tong_tien DOUBLE PRECISION NOT NULL,
  giam_gia DOUBLE PRECISION DEFAULT 0,
  phuong_thuc_thanh_toan VARCHAR(100),
  ghi_chu TEXT,
  CONSTRAINT fk_hoa_don_khach_hang
    FOREIGN KEY (id_kh) REFERENCES khach_hang (id_kh)
    ON UPDATE CASCADE,
  CONSTRAINT fk_hoa_don_nhan_vien
    FOREIGN KEY (id_nhan_vien) REFERENCES nhan_vien (id_nhan_vien)
    ON UPDATE CASCADE
);

CREATE TABLE lo_san_pham (
  id_lo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sp INTEGER NOT NULL,
  id_phieu_nhap INTEGER NOT NULL,
  so_luong_nhap INTEGER NOT NULL,
  so_luong_con INTEGER NOT NULL,
  don_gia_nhap DOUBLE PRECISION NOT NULL,
  ngay_nhap TIMESTAMP,
  ngay_san_xuat TIMESTAMP,
  han_su_dung TIMESTAMP,
  CONSTRAINT fk_lo_san_pham_sp
    FOREIGN KEY (id_sp) REFERENCES san_pham (id_sp)
    ON UPDATE CASCADE,
  CONSTRAINT fk_lo_san_pham_phieu_nhap
    FOREIGN KEY (id_phieu_nhap) REFERENCES phieu_nhap (id_phieu_nhap)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE chi_tiet_phieu_nhap (
  id_chi_tiet_nhap INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_phieu_nhap INTEGER NOT NULL,
  id_sp INTEGER NOT NULL,
  so_luong INTEGER NOT NULL,
  don_gia_nhap DOUBLE PRECISION NOT NULL,
  thanh_tien DOUBLE PRECISION NOT NULL,
  ngay_nhap TIMESTAMP,
  CONSTRAINT fk_ctpn_phieu_nhap
    FOREIGN KEY (id_phieu_nhap) REFERENCES phieu_nhap (id_phieu_nhap)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ctpn_san_pham
    FOREIGN KEY (id_sp) REFERENCES san_pham (id_sp)
    ON UPDATE CASCADE
);

CREATE TABLE chi_tiet_hoa_don (
  id_chi_tiet INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_hoa_don INTEGER NOT NULL,
  id_sp INTEGER NOT NULL,
  don_gia DOUBLE PRECISION NOT NULL,
  so_luong INTEGER NOT NULL,
  thanh_tien DOUBLE PRECISION NOT NULL,
  CONSTRAINT fk_cthd_hoa_don
    FOREIGN KEY (id_hoa_don) REFERENCES hoa_don (id_hoa_don)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_cthd_san_pham
    FOREIGN KEY (id_sp) REFERENCES san_pham (id_sp)
    ON UPDATE CASCADE
);

CREATE TABLE "user" (
  id_user INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  vai_tro VARCHAR(50) NOT NULL,
  id_nhan_vien INTEGER,
  CONSTRAINT fk_user_nhan_vien
    FOREIGN KEY (id_nhan_vien) REFERENCES nhan_vien (id_nhan_vien)
    ON DELETE SET NULL ON UPDATE CASCADE
);